name: Build solution
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches:
    - dev
    - 'releases/**'
  pull_request:
    branches: [ "dev", "master", "releases/**" ]

jobs:
  call-build:
    uses: Yvand/EntraCP/.github/workflows/reusable-build.yml@dev
    with:
      project-name: ${{ vars.PROJECT_NAME }}
      release-version: ${{ vars.RELEASE_VERSION }}
      is-production-release: false
    secrets:
      base64-encoded-signingkey: ${{ secrets.BASE64_ENCODED_SIGNINGKEY }}
