name: Build solution
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches:
    - dev
    - 'releases/**'
    tags:
      - "v*"
  pull_request:
    branches: [ "dev", "master", "releases/**" ]

jobs:
  call-build:
    uses: Yvand/EntraCP/.github/workflows/reusable-build.yml@dev
    with:
      project_name: ${{ vars.PROJECT_NAME }}
    secrets:
      base64_encoded_signingkey: ${{ secrets.BASE64_ENCODED_SIGNINGKEY }}
