name: Run Visual Studio tests
on:
  workflow_dispatch:
    inputs:
      runner_environment:
        description: 'Custom label assigned to the Windows x64 runner for this test environment'
        required: true
        type: string
permissions: {}
jobs:
  call-workflow-run-tests:
    uses: ./.github/workflows/reusaable-run-tests-on-runner.yml
    with:
      test_project_folder_name: 'Yvand.EntraCP-unit-tests'
      runner_environment: ${{ inputs.runner_environment }}
